[client]
showSidebarNavigation = false

[server]
# Increase upload size limit for recipe images (in MB)
maxUploadSize = 200
# Enable XSRF protection for security
enableXsrfProtection = true
# Run on save for better development experience
runOnSave = true

[theme]
# Dark mode theme colors
primaryColor = "#FF6B6B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"